### ISSUE TITLE
Sociotal mobile app fails to send data

### ISSUE THREAD

**Issue by snillocmot** [sociotal/mobile-environment#1]
As an authenticated and functional WUE user account I cannot use the mobile test device to send data.

When the ‘Click me’ button is pressed a grey toast pop up is presented with no string value and the sociotal platform does not receive any data. Using the API's work fine.

I am using an Huawei P7 Ascend running Android version 4.4.2.

Upon observing the debug output of Logcat the following is displayed:

_W/System.err(17248): java.io.FileNotFoundException: http://193.144.201.50:3500/SocIoTal_COMM_V1/TOKEN/simpleRequest
W/System.err(17248):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
W/System.err(17248):     at es.unican.sociotal.sociotal.classes.ClientHttp.methodPost(ClientHttp.java:55)
W/System.err(17248):     at es.unican.sociotal.sociotal.MainActivity$AsyncCallWS.doInBackground(MainActivity.java:130)
W/System.err(17248):     at es.unican.sociotal.sociotal.MainActivity$AsyncCallWS.doInBackground(MainActivity.java:117)
W/System.err(17248):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err(17248):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(17248):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(17248):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(17248):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(17248):     at java.lang.Thread.run(Thread.java:841)_

**Comment by IEMaestro** [comment]
THe problem relies on the URL you're redirecting your request. 193.144.201.50 is an internal (SocIoTal project) instance of the Context Manager that normal users are not allowed to use. Please, use "platform.sociotal.eu" instead. Sorry of this later reply. This issue should be reported in the Context Manager folder.
